export const GET_POKEMONS = "GET_POKEMONS";
export const POKEMON_DETAIL = "POKEMON_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const FILTER_POKEMONS = "FILTER_POKEMONS";
export const SORT_POKEMON = "SORT_POKEMON";
